### ISSUE TITLE
Does it compatible with OpenIdentityPlatform/OpenAM?

### ISSUE THREAD

**Issue by Evgenyx82** [ForgeRock/forgerock-javascript-sdk#32]
Hi there, we have https://github.com/OpenIdentityPlatform/OpenAM successfully installed and running. Now we need some javascript sdk. This sdk is compatible with https://github.com/OpenIdentityPlatform/OpenAM?

**Comment by jaredjensen** [comment]
The SDK is designed to be compatible with ForgeRock's Identity Stack.  There are no plans to test against OpenIdentityPlatform/OpenAM.
